version: "3.7"

services:
  backend:
    image: masquediez/asistente_backend:v1
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    image: masquediez/asistente_frontend:v1
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always
