version: "3.7"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myusern8n
      POSTGRES_PASSWORD: mypasswordn8n
      POSTGRES_DB: mydbn8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - monitoring
    deploy:
      replicas: 1

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=secretpassword
      - N8N_HOST=https://n8nencasa.duckdns.org
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8nencasa.duckdns.org
      - GENERIC_TIMEZONE=Europe/Berlin
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/n8n/.n8n
    networks:
      - monitoring
    deploy:
      replicas: 1

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "p4ssw0rd"
    ports:
      - "8200:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - monitoring
    deploy:
      replicas: 1

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    deploy:
      replicas: 1

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring
    deploy:
      replicas: 1

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
    deploy:
      replicas: 1

  postgres-exporter:
    image: wrouesnel/postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://myusern8n:mypasswordn8n@postgres:5432/mydbn8n"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - monitoring
    deploy:
      replicas: 1

networks:
  monitoring:
    external: true  # Indica que esta red es externa y debe existir en el Swarm

volumes:
  postgres_data:
  n8n_data:
  pgadmin_data:
  grafana_data:
