version: "3.7"

services:
  backend:
    image: masquediez/asistente_backend:v1
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production
    networks:
      - monitoring
    deploy:
      replicas: 3  

  frontend:
    image: masquediez/asistente_frontend:v1
    ports:
      - "3000:3000"
    networks:
      - monitoring
    deploy:
      replicas: 3

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - monitoring
    deploy:
      replicas: 3

networks:
  monitoring:
    external: true
